baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Gists'
theme = 'hugo-book'

enableGitInfo = true


[markup.goldmark.renderer]
  unsafe = true

[params]
    BookTheme = 'dark'

    BookSection = 'docs'

    BookDateFormat = 'January 2, 2006'